import Store from 'electron-store'

export interface LubanExportSettings {
  intermediateDataDir?: string
  intermediateSchemaDir?: string
  lubanDllPath?: string
  lubanConfPath?: string
  runLuban?: boolean
  outputCodeDir?: string
  outputDataDir?: string
  target?: string
  moduleName?: string
  codeTarget?: string
  dataTargets?: string[]
}

/** Local-only row fingerprints after last successful Feishu sync (per file → table → rowKey → hash) */
export type FeishuRowHashStore = Record<string, Record<string, Record<string, string>>>

export type FeishuSyncStatusLight =
  | 'none'
  | 'syncing'
  | 'ok'
  | 'error'
  | 'conflict'
  | 'disconnected'

export interface FeishuFileSyncStatus {
  filePath: string
  linked: boolean
  light: FeishuSyncStatusLight
  message?: string
  lastSyncedAt?: number
  lastError?: string
}

interface CopiperSchema {
  recentFiles: Record<string, string[]>
  exportSettings: {
    defaultFormats: ('python' | 'json' | 'luban')[]
    pythonHeader: string
    exportSubDir: string
    luban?: LubanExportSettings
  }
  /** Local Feishu row hashes — not shared in jdb */
  feishuRowHashes: FeishuRowHashStore
  /** Runtime status cache for UI lights */
  feishuStatusByFile: Record<string, FeishuFileSyncStatus>
}

export const copiperStore = new Store<CopiperSchema>({
  name: 'copiper',
  schema: {
    recentFiles: {
      type: 'object',
      default: {}
    },
    exportSettings: {
      type: 'object',
      default: {
        defaultFormats: ['python'],
        pythonHeader:
          '# Auto generated by CoPiper, do not edit it. Unless you know what you are doing for sure.',
        exportSubDir: '',
        luban: {
          runLuban: true,
          moduleName: 'jdb',
          target: 'all',
          codeTarget: 'cpp-sharedptr-bin',
          dataTargets: ['bin', 'json']
        }
      },
      properties: {
        defaultFormats: { type: 'array', items: { type: 'string' } },
        pythonHeader: { type: 'string' },
        exportSubDir: { type: 'string' },
        luban: { type: 'object' }
      }
    },
    feishuRowHashes: {
      type: 'object',
      default: {}
    },
    feishuStatusByFile: {
      type: 'object',
      default: {}
    }
  }
})

export function getRecentFiles(workspacePath: string): string[] {
  const all = copiperStore.get('recentFiles')
  return all[workspacePath] || []
}

export function addRecentFile(workspacePath: string, filePath: string): void {
  const all = copiperStore.get('recentFiles')
  const list = all[workspacePath] || []
  const filtered = list.filter((f) => f !== filePath)
  filtered.unshift(filePath)
  // Keep at most 20 recent files per workspace
  all[workspacePath] = filtered.slice(0, 20)
  copiperStore.set('recentFiles', all)
}

export function getExportSettings(): CopiperSchema['exportSettings'] {
  return copiperStore.get('exportSettings')
}

export function setExportSettings(
  settings: Partial<CopiperSchema['exportSettings']>
): void {
  const current = copiperStore.get('exportSettings')
  const next = {
    ...current,
    ...settings,
    luban: settings.luban
      ? { ...(current.luban || {}), ...settings.luban }
      : current.luban
  }
  copiperStore.set('exportSettings', next)
}

// ── Feishu sync local state (row fingerprints + status lights) ──

export function getRowHashes(filePath: string): Record<string, Record<string, string>> {
  const all = copiperStore.get('feishuRowHashes') || {}
  return all[filePath] || {}
}

export function setRowHashes(
  filePath: string,
  hashes: Record<string, Record<string, string>>
): void {
  const all = { ...(copiperStore.get('feishuRowHashes') || {}) }
  all[filePath] = hashes
  copiperStore.set('feishuRowHashes', all)
}

export function getFileSyncStatus(filePath: string): FeishuFileSyncStatus | undefined {
  const all = copiperStore.get('feishuStatusByFile') || {}
  return all[filePath]
}

export function setFileSyncStatus(filePath: string, status: FeishuFileSyncStatus): void {
  const all = { ...(copiperStore.get('feishuStatusByFile') || {}) }
  all[filePath] = status
  copiperStore.set('feishuStatusByFile', all)
}

export function getAllFileSyncStatuses(): Record<string, FeishuFileSyncStatus> {
  return copiperStore.get('feishuStatusByFile') || {}
}
