import type { HermesProviderMeta } from '../../types/hermes'

export const HERMES_PROVIDER_REGISTRY: HermesProviderMeta[] = [
  {
    id: 'anthropic',
    group: 'hosted',
    authType: 'api_key',
    titleKey: 'hermes.provider.anthropic.title',
    descriptionKey: 'hermes.provider.anthropic.desc',
    badgeKey: 'hermes.auth.apiKey',
    modelSummaryKey: 'hermes.provider.anthropic.summary',
    docsUrl: 'https://hermes-agent.nousresearch.com/docs/integrations/providers#anthropic-native',
    defaultModel: 'claude-sonnet-4-20250514',
    recommendedModels: [
      { value: 'claude-sonnet-4-20250514', label: 'Claude Sonnet 4' },
      { value: 'claude-opus-4-20250514', label: 'Claude Opus 4' },
      { value: 'claude-3-5-haiku-20241022', label: 'Claude Haiku 3.5' },
    ],
    fields: [],
  },
  {
    id: 'openai',
    group: 'hosted',
    authType: 'api_key',
    titleKey: 'hermes.provider.openai.title',
    descriptionKey: 'hermes.provider.openai.desc',
    badgeKey: 'hermes.auth.apiKey',
    modelSummaryKey: 'hermes.provider.openai.summary',
    docsUrl: 'https://hermes-agent.nousresearch.com/docs/integrations/providers',
    defaultModel: 'gpt-4.1',
    recommendedModels: [
      { value: 'gpt-4.1', label: 'GPT-4.1' },
      { value: 'gpt-4o', label: 'GPT-4o' },
      { value: 'gpt-5-mini', label: 'GPT-5 Mini' },
    ],
    fields: [],
  },
  {
    id: 'openrouter',
    group: 'hosted',
    authType: 'api_key',
    titleKey: 'hermes.provider.openrouter.title',
    descriptionKey: 'hermes.provider.openrouter.desc',
    badgeKey: 'hermes.auth.apiKey',
    modelSummaryKey: 'hermes.provider.openrouter.summary',
    docsUrl: 'https://hermes-agent.nousresearch.com/docs/integrations/providers',
    defaultModel: 'anthropic/claude-sonnet-4',
    recommendedModels: [
      { value: 'anthropic/claude-sonnet-4', label: 'Claude Sonnet 4' },
      { value: 'openai/gpt-4.1', label: 'GPT-4.1' },
      { value: 'google/gemini-2.5-pro', label: 'Gemini 2.5 Pro' },
    ],
    fields: [],
  },
  {
    id: 'xai',
    group: 'hosted',
    authType: 'api_key',
    titleKey: 'hermes.provider.xai.title',
    descriptionKey: 'hermes.provider.xai.desc',
    badgeKey: 'hermes.auth.apiKey',
    modelSummaryKey: 'hermes.provider.xai.summary',
    docsUrl: 'https://hermes-agent.nousresearch.com/docs/integrations/providers#xai-grok--responses-api--prompt-caching',
    defaultModel: 'grok-4-1-fast-reasoning',
    recommendedModels: [
      { value: 'grok-4-1-fast-reasoning', label: 'Grok 4.1 Fast Reasoning' },
      { value: 'grok-4-fast-reasoning', label: 'Grok 4 Fast Reasoning' },
    ],
    fields: [],
  },
  {
    id: 'gemini-api',
    group: 'hosted',
    authType: 'api_key',
    titleKey: 'hermes.provider.geminiApi.title',
    descriptionKey: 'hermes.provider.geminiApi.desc',
    badgeKey: 'hermes.auth.apiKey',
    modelSummaryKey: 'hermes.provider.geminiApi.summary',
    docsUrl: 'https://hermes-agent.nousresearch.com/docs/integrations/providers',
    defaultModel: 'gemini-2.5-pro',
    recommendedModels: [
      { value: 'gemini-2.5-pro', label: 'Gemini 2.5 Pro' },
      { value: 'gemini-2.5-flash', label: 'Gemini 2.5 Flash' },
      { value: 'gemini-2.0-flash', label: 'Gemini 2.0 Flash' },
    ],
    fields: [],
  },
  {
    id: 'bedrock',
    group: 'hosted',
    authType: 'aws',
    titleKey: 'hermes.provider.bedrock.title',
    descriptionKey: 'hermes.provider.bedrock.desc',
    badgeKey: 'hermes.auth.aws',
    modelSummaryKey: 'hermes.provider.bedrock.summary',
    docsUrl: 'https://hermes-agent.nousresearch.com/docs/integrations/providers#aws-bedrock',
    defaultModel: 'anthropic.claude-3-7-sonnet-20250219-v1:0',
    recommendedModels: [
      { value: 'anthropic.claude-3-7-sonnet-20250219-v1:0', label: 'Claude 3.7 Sonnet' },
      { value: 'us.amazon.nova-pro-v1:0', label: 'Amazon Nova Pro' },
      { value: 'us.deepseek.r1-v1:0', label: 'DeepSeek R1' },
    ],
    fields: [
      { key: 'region', labelKey: 'hermes.field.awsRegion', type: 'text', placeholder: 'us-east-1' },
      { key: 'profile', labelKey: 'hermes.field.awsProfile', type: 'text', placeholder: 'default' },
    ],
  },
  {
    id: 'copilot',
    group: 'hosted',
    authType: 'oauth',
    titleKey: 'hermes.provider.copilot.title',
    descriptionKey: 'hermes.provider.copilot.desc',
    badgeKey: 'hermes.auth.oauth',
    modelSummaryKey: 'hermes.provider.copilot.summary',
    docsUrl: 'https://hermes-agent.nousresearch.com/docs/integrations/providers#github-copilot',
    defaultModel: 'gpt-4.1',
    recommendedModels: [
      { value: 'gpt-4.1', label: 'GPT-4.1' },
      { value: 'claude-sonnet-4', label: 'Claude Sonnet 4' },
      { value: 'gemini-2.5-pro', label: 'Gemini 2.5 Pro' },
    ],
    fields: [],
  },
  {
    id: 'ollama-cloud',
    group: 'hosted',
    authType: 'api_key',
    titleKey: 'hermes.provider.ollamaCloud.title',
    descriptionKey: 'hermes.provider.ollamaCloud.desc',
    badgeKey: 'hermes.auth.apiKey',
    modelSummaryKey: 'hermes.provider.ollamaCloud.summary',
    docsUrl: 'https://hermes-agent.nousresearch.com/docs/integrations/providers#ollama-cloud--managed-ollama-models-oauth--api-key',
    defaultModel: 'qwen3-coder:480b-cloud',
    recommendedModels: [
      { value: 'qwen3-coder:480b-cloud', label: 'Qwen3 Coder 480B Cloud' },
      { value: 'llama3.3:70b-cloud', label: 'Llama 3.3 70B Cloud' },
    ],
    fields: [],
  },
  {
    id: 'deepseek',
    group: 'hosted',
    authType: 'api_key',
    titleKey: 'hermes.provider.deepseek.title',
    descriptionKey: 'hermes.provider.deepseek.desc',
    badgeKey: 'hermes.auth.apiKey',
    modelSummaryKey: 'hermes.provider.deepseek.summary',
    docsUrl: 'https://hermes-agent.nousresearch.com/docs/integrations/providers#first-class-chinese-ai-providers',
    defaultModel: 'deepseek-chat',
    recommendedModels: [
      { value: 'deepseek-chat', label: 'DeepSeek Chat' },
      { value: 'deepseek-reasoner', label: 'DeepSeek Reasoner' },
    ],
    fields: [],
  },
  {
    id: 'minimax',
    group: 'hosted',
    authType: 'api_key',
    titleKey: 'hermes.provider.minimax.title',
    descriptionKey: 'hermes.provider.minimax.desc',
    badgeKey: 'hermes.auth.apiKey',
    modelSummaryKey: 'hermes.provider.minimax.summary',
    docsUrl: 'https://hermes-agent.nousresearch.com/docs/integrations/providers#first-class-chinese-ai-providers',
    defaultModel: 'MiniMax-M1',
    recommendedModels: [
      { value: 'MiniMax-M1', label: 'MiniMax M1' },
      { value: 'abab7-chat-preview', label: 'abab7 Chat Preview' },
    ],
    fields: [],
  },
  {
    id: 'kimi',
    group: 'hosted',
    authType: 'api_key',
    titleKey: 'hermes.provider.kimi.title',
    descriptionKey: 'hermes.provider.kimi.desc',
    badgeKey: 'hermes.auth.apiKey',
    modelSummaryKey: 'hermes.provider.kimi.summary',
    docsUrl: 'https://hermes-agent.nousresearch.com/docs/integrations/providers#first-class-chinese-ai-providers',
    defaultModel: 'moonshot-v1-128k',
    recommendedModels: [
      { value: 'moonshot-v1-128k', label: 'Moonshot 128K' },
      { value: 'moonshot-v1-32k', label: 'Moonshot 32K' },
    ],
    fields: [],
  },
  {
    id: 'qwen',
    group: 'hosted',
    authType: 'api_key',
    titleKey: 'hermes.provider.qwen.title',
    descriptionKey: 'hermes.provider.qwen.desc',
    badgeKey: 'hermes.auth.apiKey',
    modelSummaryKey: 'hermes.provider.qwen.summary',
    docsUrl: 'https://hermes-agent.nousresearch.com/docs/integrations/providers#first-class-chinese-ai-providers',
    defaultModel: 'qwen-max',
    recommendedModels: [
      { value: 'qwen-max', label: 'Qwen Max' },
      { value: 'qwen-plus', label: 'Qwen Plus' },
      { value: 'qwen-turbo', label: 'Qwen Turbo' },
    ],
    fields: [],
  },
  {
    id: 'glm',
    group: 'hosted',
    authType: 'api_key',
    titleKey: 'hermes.provider.glm.title',
    descriptionKey: 'hermes.provider.glm.desc',
    badgeKey: 'hermes.auth.apiKey',
    modelSummaryKey: 'hermes.provider.glm.summary',
    docsUrl: 'https://hermes-agent.nousresearch.com/docs/integrations/providers#first-class-chinese-ai-providers',
    defaultModel: 'glm-4.5',
    recommendedModels: [
      { value: 'glm-4.5', label: 'GLM 4.5' },
      { value: 'glm-4-air', label: 'GLM 4 Air' },
    ],
    fields: [],
  },
  {
    id: 'ark',
    group: 'hosted',
    authType: 'api_key',
    titleKey: 'hermes.provider.ark.title',
    descriptionKey: 'hermes.provider.ark.desc',
    badgeKey: 'hermes.auth.apiKey',
    modelSummaryKey: 'hermes.provider.ark.summary',
    docsUrl: 'https://hermes-agent.nousresearch.com/docs/integrations/providers#first-class-chinese-ai-providers',
    defaultModel: 'doubao-pro-32k',
    recommendedModels: [
      { value: 'doubao-pro-32k', label: 'Doubao Pro 32K' },
      { value: 'doubao-seed-1-6-thinking', label: 'Doubao Seed Thinking' },
    ],
    fields: [],
  },
  {
    id: 'google-gemini-cli',
    group: 'oauth',
    authType: 'oauth',
    titleKey: 'hermes.provider.googleOauth.title',
    descriptionKey: 'hermes.provider.googleOauth.desc',
    badgeKey: 'hermes.auth.oauth',
    modelSummaryKey: 'hermes.provider.googleOauth.summary',
    docsUrl: 'https://hermes-agent.nousresearch.com/docs/integrations/providers#google-gemini-via-oauth-google-gemini-cli',
    defaultModel: 'gemini-2.5-pro',
    recommendedModels: [
      { value: 'gemini-2.5-pro', label: 'Gemini 2.5 Pro' },
      { value: 'gemini-2.5-flash', label: 'Gemini 2.5 Flash' },
    ],
    fields: [
      { key: 'accountLabel', labelKey: 'hermes.field.oauthAccount', type: 'text', placeholder: 'user@example.com' },
    ],
  },
  {
    id: 'qwen-portal',
    group: 'oauth',
    authType: 'oauth',
    titleKey: 'hermes.provider.qwenPortal.title',
    descriptionKey: 'hermes.provider.qwenPortal.desc',
    badgeKey: 'hermes.auth.oauth',
    modelSummaryKey: 'hermes.provider.qwenPortal.summary',
    docsUrl: 'https://hermes-agent.nousresearch.com/docs/integrations/providers#qwen-portal-oauth',
    defaultModel: 'qwen-max',
    recommendedModels: [
      { value: 'qwen-max', label: 'Qwen Max' },
      { value: 'qwen-plus', label: 'Qwen Plus' },
    ],
    fields: [
      { key: 'accountLabel', labelKey: 'hermes.field.oauthAccount', type: 'text', placeholder: 'user@example.com' },
    ],
  },
  {
    id: 'ollama',
    group: 'self-hosted-compatible',
    authType: 'local',
    titleKey: 'hermes.provider.ollama.title',
    descriptionKey: 'hermes.provider.ollama.desc',
    badgeKey: 'hermes.auth.local',
    modelSummaryKey: 'hermes.provider.ollama.summary',
    docsUrl: 'https://hermes-agent.nousresearch.com/docs/integrations/providers#ollama--local-models-zero-config',
    defaultModel: 'qwen2.5:14b',
    recommendedModels: [
      { value: 'qwen2.5:14b', label: 'Qwen 2.5 14B' },
      { value: 'llama3.1:8b', label: 'Llama 3.1 8B' },
    ],
    fields: [
      { key: 'base_url', labelKey: 'hermes.field.baseUrl', type: 'text', placeholder: 'http://127.0.0.1:11434/v1' },
    ],
  },
  {
    id: 'other-compatible',
    group: 'self-hosted-compatible',
    authType: 'compatible',
    titleKey: 'hermes.provider.otherCompatible.title',
    descriptionKey: 'hermes.provider.otherCompatible.desc',
    badgeKey: 'hermes.auth.compatible',
    modelSummaryKey: 'hermes.provider.otherCompatible.summary',
    defaultModel: '',
    recommendedModels: [],
    fields: [
      { key: 'base_url', labelKey: 'hermes.field.baseUrl', type: 'text', placeholder: 'https://router.example.com/v1' },
    ],
  },
  {
    id: 'custom-openai-compatible',
    group: 'self-hosted-compatible',
    authType: 'compatible',
    titleKey: 'hermes.provider.customCompatible.title',
    descriptionKey: 'hermes.provider.customCompatible.desc',
    badgeKey: 'hermes.auth.compatible',
    modelSummaryKey: 'hermes.provider.customCompatible.summary',
    defaultModel: '',
    recommendedModels: [],
    fields: [
      { key: 'base_url', labelKey: 'hermes.field.baseUrl', type: 'text', placeholder: 'https://api.example.com/v1' },
    ],
  },
]
